### ISSUE TITLE
UI: 상세 페이지 구현

### ISSUE THREAD

**Issue by bboroin** [GOMINTAPA/GMTP#32]
## 무엇을 디자인하는지
>  고민 카드 눌렀을 때 나오는 상세 페이지 화면

## 변경 사항
- 계정 정보 섹션과 고민 내용 섹션으로 분리
  - [x] 계정 정보 섹션 : 프로필, 닉네임
  - [x] 고민 내용 섹션 : 제목, 내용
  - [x] 선택 섹션 : 선택 항목 2개
  - [ ] 키워드 섹션 : 키워드

**Comment by maruru301** [comment]
화면 연결 깜빡하고 안했어욤 ㅎㅎㅎㅎㅎ
